plugins/prettier.js
BREAKING CHANGE: rules `curly` and `quotes` reenabled
=> feat: reenable some prettier config disabled rules

@ornikar/eslint-config/rules/react.js
noSortAlphabetically option is not yet released
=> fix: disable react sort prop types

@ornikar/eslint-config/rules/react.js
We can still reenable it later with a breaking change
=> fix: disable sort prop types required first

@ornikar/eslint-config/rules/react.js
J'ai essayé mettre des options à la règle pour forcer la présence des accolades pour les childrens, mais ça fonctionne pas tout à fait comme espéré :
=> feat: disable jsx-curly-brace-presence [no issue]

@ornikar/eslint-config/rules/code-quality.js
A mon sens, cette règle a pour but de suggérer au gentil développeur qu'il pourrait être intéressant de factoriser/regrouper. L'erreur est donc trop forte et un warning serait plus pertinent.
=> fix: max-lines triggers warning instead of error

@ornikar/postcss-config/index.js, @ornikar/postcss-config/package.json
BREAKING CHANGE: removed export productionPlugins
cssnano should be called with https://github.com/NMFR/optimize-css-assets-webpack-plugin
=> fix: remove postcss production

@ornikar/renovate-config/package.json
Avoid a lot of workflows during the day
We can still do it with the checkbox in the PR when we need it :)
=> feat(renovate-config): disable rebase stale pr

@ornikar/eslint-config/react.js
BREAKING CHANGE: if you use react, you will also need to run `yarn add --dev eslint-plugin-react-hooks`
=> feat: add eslint-plugin-react-hooks [no issue]

@ornikar/renovate-config/package.json
J'avais trouvé cette issue suite à une recherche google :
https://github.com/renovatebot/renovate/issues/2714
Je pense pas qu'on puisse faire de distinction entre un schedule d'ouverture de PR et un schedule de rebase.
Avec ce que j'ajoute, l'effet escompté est que : 
- Les PR de renovate sont toujours ouverte `earlyMondays` 
- Les PR ne sont pas mise à jour automatique en dehors des `earlyMondays` 
- Les PR de la semaine précédentes sont mise à jour lors des `earlyMondays`
Les PR ne sont pas censées resté ouvertes plus d'une semaine, mais bon ça arrive et ça arrivera encore je pense.
=> feat: rebase stale pr on early mondays [no issue]

@ornikar/renovate-config/package.json
Permet de créer des groupes de packages pour renovate et éviter d'avoir 5 PR pour eslint/babel/storybook.
J'ai voulu rajouter webpack mais c'est utilisé que sur la LA. Et y a pas vraiment de convention de ming.. Est ce que je le rajoute quand même ?
=> feat: group packages renovate ONK-3275

@ornikar/renovate-config/package.json
C'est qque chose dont on avait parlé, mais j'avais pas crée de tâche pour.
De base les valeurs sont : 
```
"prConcurrentLimit": 20,
"prHourlyLimit": 2,
```
cf : https://renovatebot.com/docs/presets-config/#configbase
=> feat: increase PR limits [no issue]

@ornikar/eslint-config-babel/README.md, @ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-node/README.md, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config-react/README.md, @ornikar/eslint-config-react/index.js, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/README.md, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/README.md, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/README.md, @ornikar/eslint-config/package.json, yarn.lock
https://ornikar.atlassian.net/browse/ONK-3265
Configs & plugins deviennent des dependencies + update des readme
Pour `eslint-config`, j'ai retiré les devDeps/Deps suivantes, car elles me semblent superflue : 
- `eslint-config-react`
- `eslint-plugin-node`
=> refactor: eslint-config dependencies ONK-3265

@ornikar/eslint-config-react/index.js, @ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/package.json, yarn.lock
En pratique, on peut aujourdhui pas les ignorer, car sela revient à ne pas les utiliser. Par contre, je cache leurs props.
https://github.com/airbnb/enzyme/issues/2103
J'ai également rajouté une option `ignore` et `componentToTest`, qui permet d'avoir des snapshots des composants et non des stories
=> feat: ignore decorators in snapshots [no issue]

@ornikar/eslint-config-typescript/index.js
https://github.com/typescript-eslint/typescript-eslint/issues/201
private is comming in js world and no-public will be the most common way to read a js file (and probably ts too)
BREAKING CHANGE: typescript-eslint/explicit-member-accessibility rule changed
=> feat: explicit-member-accessibility to no-public [no issue]

@ornikar/eslint-config/rules/best-practices.js, @ornikar/stylelint-config/index.js
Adds 2 small rules regarding code comments:
- **eslint**: `no-warning-comments`: no more `todo`, `fixme` or `xxx` in commlent (at the beginning)
- **stylelint**: `comment-word-blacklist`: no more `todo`, `fixme`
Motivations:
> - if this is to fix/todo, just fix or do before pushing on production :)
> - don't foget anything todo/tofix before pushing in production
> - nice extension for VSCode users: [todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) to have a good overview of your remaining TODO in your code
=> feat: clean comments [no issue]

renovate.json
Les PR ne sont plus ouvertes automatiquement le lundi, car elles doivent être auparavant approve dans la master issue. Je pense qu'il vaut mieux désactiver cette option.
Cf la [doc](https://github.com/renovatebot/renovate/blob/956445eee424e12cf1ab80c160137ea6fd620dcb/website/docs/configuration-options.md#masterissueapproval) qui a enfin été mis à jour ^^
Desactiver l'option masterIssueApproval
=> fix: remove masterIssueApproval option [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/addon-knobs.js, @ornikar/jest-config-react/jest-preset.js
Pour learner-app, on utilise beacoup les knobs dans les stories ce qui fait planter les snapshots lorsqu'on met a jour la config jest
Implémentation du mock
=> feat: support addon knobs [no issue]

@ornikar/jest-config/jest-preset.js
Il y avait une coquille dans la config jest. Le nom d'un fichier a été modifié mais son import n'a pas été changé en conséquence.
Changement de l'import
=> fix: use new file name [no issue]

@ornikar/renovate-config/package.json
Nous avons décidé lors du dernier grooming front d'activer la master issue sur tout nos répos
Activer l'option dans le preset renovate.
=> feat: enable master issue in renovate preset [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
L'application des decorateurs rend les snapshots inutilisables, a cause du shallow. Permet également d'ignorer lorsqu'il n'y a que des decorateurs de layout.
Ajoute une option qui ignore les decorateurs pour les stories qui n'en ont pas besoin en attendant un fix par enzyme
=> feat: add option to ignore all decorators [no issue]

renovate.json
Option activé dans notre preset (publié). Il n'est plus nécessaire de l'activer manuellement sur le repo.
Retirer le preset :masterIssue du renovate.json, car configuré par notre preset interne.
=> chore: remove redundant masterissue config [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
https://github.com/airbnb/enzyme/pull/1966 a été mergée et dispo depuis les derniers plateform days
Les snapshots ont maintenant une utilitée !
Exemple: 
● sections/Instructor/CommentsDrawer/Comment › No Author
```diff
- Snapshot
+ Received
- <div>
-   <ContextProvider>
-     <MockResults>
-       <JestStoryWrapper>
-         <Comment
-           comment={
-             CommentResource {
-               "author": null,
-               "comment": "Contenu du commentaire.",
-               "created_at": "2014-12-17 17:11:29",
-               "id": 4,
-               "updated_at": "2014-12-17 17:11:29",
-               Symbol(Defined Members): Array [
-                 "id",
-                 "comment",
-                 "created_at",
-                 "updated_at",
- …
```
=> fix: shallow snapshots with decorators [no issue]

@ornikar/eslint-config-babel-use/index.js
Ne pas nommer un composant react rend le debug plus compliqué car ils apparaitront comme anonymes dans les stacktrace react.
Cette règle eslint force à nommer toutes les fonctions exportés. Cela concerne donc une majorité des composants (certains ne sont pas exportés) et une majorité des fonctions (certaines ne sont pas des composants react, mais c'est pas plus mal de les nommer aussi pour les stacks js)
=> feat: enable import/no-anonymous-default-export for functions [no issue]

@ornikar/eslint-config/package.json, yarn.lock
Lorsque l'on exporte un type dans un fichier typescript, il n'est pas reconnu par eslint lorsqu'on l'importe ailleurs.
Mise à jour de eslint-plugin-import dans eslint-config
=> chore: update eslint-plugin-import to fix typescript issue [no issue]

@ornikar/eslint-config/plugins/unicorn.js
Désactivation de la règle `prefer-event-key`
Certains navigateurs ne supportent pas encore l'attribut `key`
=> fix: disable prefer-event-key rule [no issue]

@ornikar/renovate-config/package.json
Passer d'un rythme de renovate à 1 fois / 2 semaines à 1 fois / semaine.
[JIRA issue: ONK-3841](https://ornikar.atlassian.net/browse/ONK-3841)
=> fix: raise renovate scheduled to every week on monday ONK-3841

@ornikar/jest-config-react/__mocks__/@storybook/react.js
Ajout de la propriété name aux paramètres passés par notre mock de @storybook/react.
Permettra d'éviter une erreur jest dans Kitt.
=> fix: add storyname to parameters [no issue]

@ornikar/renovate-config/package.json
Les packages `@types/*` peuvent etre automergés s'ils passent la validation de `tsc`
=> feat: renovate automerge types [no issue]

@ornikar/eslint-config-typescript/index.js
La version d'Omit inclue dans typescript n'est pas stricte. Voir issue https://github.com/microsoft/TypeScript/issues/30825
Eslint permet de bannir ce type: https://github.com/microsoft/TypeScript/issues/30825#issuecomment-508584855
=> feat: ban typescript Omit type [no issue]

@ornikar/eslint-config-typescript-react/index.js
Plus besoin d'utiliser les propTypes quand on utilise typescript
Désactivation de la règle react/prop-types dans la configuration eslint Typescript x React
=> feat: disable prop types rule in eslint ts config [no issue]

@ornikar/eslint-config-typescript/index.js
Pour pouvoir typer la déclaration d'une fonction et ne pas avoir à typer en plus le retour de cette fonction
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md#allowtypedfunctionexpressions
Ajout de la règle `explicit-function-return-type` avec l'option `allowTypedFunctionExpressions`
=> feat: add explicit function return type rule [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/jest-preset.js, @ornikar/jest-config-react/package.json, @ornikar/jest-config/jest-preset.js
Use presence of lerna.json to detect a lerna repo.
Also remove detections in jest-config-react and use a replace string method instead
Also add support for `addWithPercyOptions`, used in components
[JIRA issue: ONK-3913](https://ornikar.atlassian.net/browse/ONK-3913)
=> feat: support lerna in jest configs ONK-3913

@ornikar/rollup-config/createRollupConfig.js
On this [PR](https://github.com/ornikar/components/pull/329) => the node builds fail when parsing css files.
I'm not exactly sure why, but if you ignore .css imports in node builds, the postCSSPlugin plugin still runs on those files & crashes.
**Node builds** => Ignore css & no postCSSPlugin
**Browser builds** => Use postCSSPlugin
=> fix: dont use postCss plugin in node builds, css is not imported [no issue]

@ornikar/jest-config-react/jest-preset.js
Jest crashes when our stories import svg files.
Mock import of svg files in Jest config
=> fix: add svg import mock in jest config [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
It doesn't work, or i can't make it work 😕 
Remove usage of this plugin in rollup config.
=> fix: remove rollup plugin ignore import dep & usage [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
Proptypes aren't removed from built files
See : https://circleci.com/gh/ornikar/components/7822?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Add a babel plugin that removes proptypes from built files
=> fix: add remove-proptype babel plugin [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
https://github.com/egoist/rollup-plugin-postcss/pull/131
fix pour kitt
https://www.chromaticqa.com/snapshot?appId=5d25e603d7f87800202b6da0&id=5d4ade5ee960ee0020ca5e25
=> fix: bring back same fix for postcss module order [no issue]

@ornikar/repo-config/createLintStagedConfig.js
`}` missing for json config files
=> fix: createLintStagedConfig missing } for json [no issue]

@ornikar/repo-config-react/createLintStagedConfig.js
Sur les projet sans TypeScript, des fichiers .css.d.ts sont créés et ajoutés aux commits.
Limiter l'exécution du linter css ts en fonction de la présence de TypeScript dans le projet.
=> chore: execute typescript css linter if typescript exists in project

@ornikar/repo-config/createLintStagedConfig.js
We could not do this before because that would have mean yarn could run twice in the same time, but now we can use callbacks to make it run only once !
=> fix: run yarn-update-lock on package.json changes [no issue]

@ornikar/repo-config-react/createLintStagedConfig.js
repo-config-react 1.0.1 does not work :)
It crashes when reading the properties of `pkg = JSON.stringify('...')`
`package.json` should be parsed, not stringified.
=> fix: parse JSON file instead of stringifying it [no issue]

@ornikar/renovate-config/package.json
minor generally is the same as the lib ? so it should be synced to the package installed, not auto merged (for example we should not install @types/react@16.9 unless we also have react 16.9)
=> fix(renovate-config): only patch should be merged automaticly for @types [no issue]

@ornikar/storybook-config/package.json, @ornikar/storybook-config/webpack-configs/lib.js, yarn.lock
the 5.2 version has a better typescript compatibility
BREAKING CHANGE: because of new css-loader major, it requires storybook 5.2 and is not compatible with previous versions
- because of new css-loader major, it requires storybook 5.2 and is not compatible with previous versions (e72181753997f2aff3d2a3525b31fbfb985169d8)
=> fix(storybook-config): update for storybook 5.2 [no issue]

@ornikar/renovate-config/package.json
Packages `react`, `react-dom` and their types should be updated at the same time
=> fix(renovate-config): group react and react types packages [no issue]

@ornikar/jest-config-react/jest-preset.js
En utilisant transform, on override la config de base de jest. Ca ne posait pas de soucis sur craco car cra reconfigure bien, par contre sur un projet non craco ca ne marchait pas (plus de transformation babel-jest)
Configuration pour babel-jest
Testé sur kitt et components
=> fix(jest-config-react): preset for non craco configs [no issue]

@ornikar/rollup-config/createRollupConfig.js
Les fichiers dist/styles.css dans les components ne sont aujourdhui pas compilés, depuis la branche typescript
Il semblerait que la config postcss n'est pas bien chargée. 
Chargement de la config avec un require, et passage de plugins directement. Cela évite également de faire le calcul coté plugin postcss plusieurs fois (1 pour chaque package) :)
=> fix(rollup-config): load postcss config [no issue]

@ornikar/repo-config/createLintStagedConfig.js
Because yarn and prettier both run at the same time, the resulted package.json could be formatted by either yarn or prettier depending on the PR
The formatting of package.json is done after yarn-update-lock
=> fix: package json lint-staged racing condition [no issue]

@ornikar/repo-config/package.json, yarn.lock
dep utilisée ici https://github.com/ornikar/shared-configs/blob/master/%40ornikar/repo-config/createHuskyConfig.js#L19, qui, utilisé dans un projet où aucune autre dep a besoin de cross-env, fait planter le push.
Ajout dans le package.json
=> fix: missing dep cross-env [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/package.json, yarn.lock
BREAKING CHANGE: new peer dependency of @testing-library/react
- enzyme a des limitations notament pour les contextes react qui ne marchent pas correctement
- les decorateurs globaux permettent de rajouter un (ou des) contexte(s) react tel que intl
Utilisation de react-testing-library. C'est une option pour l'instant car ca change totalement le snapshot et le rendu n'est plus shallow, ce qui peut poser des problemes sur certaines stories qu'on a
- new peer dependency of @testing-library/react (95ca216c12cb5e02fefc790b7ff36f9fb39cddc7)
=> feat: global decorators and react-testing-library [no issue]

@ornikar/jest-config/test-setup-after-env.js
Some tests fail because react throws warning when libraries use deprecated lifecycle methods.
Ignore those lifecycle warning in jest tests, they are already forbidden by our eslint config.
=> feat: ignore lifecycle methods warning in jest tests [no issue]

@ornikar/jest-config/test-shim.js
global.Intl = IntlPolyfill écrase les changements fait par le polyfill de pluralRules. J'ai testé en local en linkant jest-config et ça marche de mon côté
=> fix: import order matters [no issue]

@ornikar/intl-config/generate-translations.js
Pour un test j'ai besoin de passer des options au plugin babel
=> feat(intl-config): add babelPluginReactIntlOptions in generate-translations script [no issue]

@ornikar/jest-config/test-setup-after-env.js
~Je sais pas comment ca pouvait marcher avant, mais~ j'ai des calls stack recursive sur certaines versions de node 10 et 12
```
RangeError: Maximum call stack size exceeded
at deprecatedReactLifeCycleMethods.some (node_modules/@ornikar/jest-config/test-setup-after-env.js:28:46)
at Array.some (<anonymous>)
at BufferedConsole.newMethod [as warn] (node_modules/@ornikar/jest-config/test-setup-after-env.js:28:41)
at BufferedConsole.newMethod [as warn] (node_modules/@ornikar/jest-config/test-setup-after-env.js:36:25)
at BufferedConsole.newMethod [as warn] (node_modules/@ornikar/jest-config/test-setup-after-env.js:36:25)
at BufferedConsole.newMethod [as warn] (node_modules/@ornikar/jest-config/test-setup-after-env.js:36:25)
at BufferedConsole.newMethod [as warn] …
```
=> fix: recursive warn [no issue]

@ornikar/rollup-config/createRollupConfig.js
ignore `.eslintrc.project.json` that I added in components in https://github.com/ornikar/components/pull/450
=> feat(rollup-config): packages filter ignore name starting with .eslintrc [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
We're currently generating snapshots from stories.
We used to do it using enzyme and in some cases, with react testing library.
-> We want to only use react testing library, so we make it the default behavior
See what we get with this : https://github.com/ornikar/learner-webapp/pull/827
* Remove default enzyme ✂️ 
* Default to react-testing-library 🌠 
[JIRA issue: ONK-4263](https://ornikar.atlassian.net/browse/ONK-4263)
=> feat: use react testing library instead of enzyme ONK-4263

@ornikar/jest-config-react/__mocks__/@storybook/react.js
Prevents unwanted errors, because cleanup effects are not triggered
=> fix: unmount components after rendering them [no issue]

@ornikar/jest-config/package.json, @ornikar/jest-config/test-shim.js, yarn.lock
Since node 12, we no longer need polyfills, just node-icu to load fr data
BREAKING CHANGE: project should add a devdep to node-icu and run commands with NODE_ICU_DATA env variable
- project should add a devdep to node-icu and run commands with NODE_ICU_DATA env variable (45bf7ab787976a6b40f0862185f163cc1a04c77c)
=> feat: remove intl polyfill [no issue]

@ornikar/lerna-config/generate-tsconfig-files.js
allow @ornikar/shared-config to work on both components and kitt
- allow to import the current package directly (used in kitt in stories to target built file, but tsc should target src)
- build definitions in dist/definitions (breaking)
- add files in exclude
=> fix: tsconfig generator [no issue]

@ornikar/eslint-config-typescript/plugins/typescript-eslint.js
Examples of correct code for this rule with { allowExpressions: true }:
```
node.addEventListener('click', () => {});
node.addEventListener('click', function () {});
```
Aujourdhui on doit faire:
```
node.addEventListener('click', (): void => {});
node.addEventListener('click', function (): void {});
```
=> feat: avoir typing return type when expression typed [no issue]

@ornikar/browserslist-config/package.json, @ornikar/commitlint-config/package.json, @ornikar/eslint-config-babel-use/package.json, @ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-formatjs/package.json, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/package.json, @ornikar/intl-config/package.json, @ornikar/jest-config-react/package.json, @ornikar/jest-config/package.json, @ornikar/lerna-config/package.json, @ornikar/postcss-config/package.json, @ornikar/prettier-config/package.json, @ornikar/renovate-config/package.json, @ornikar/repo-config-react/package.json, @ornikar/repo-config/package.json, @ornikar/rollup-config/package.json, @ornikar/stylelint-config/package.json, @ornikar/webpack-config/package.json, package.json
Some renovate prs fails because of node version: https://github.com/ornikar/components/pull/516#issuecomment-633433095
requires node 12.16.1 instead of 12.16.2
=> feat: support node 12.16.1 for renovate [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/package.json, yarn.lock
We have a lot of snapshots showing loading state or empty component because apollo is not in its final state
> Loading state, while important, isn't the only thing to test. To test the final state of the component after receiving data, we can just wait for it to update and test the final state.
> Here, you can see the await wait(0) line. This is a utility function from the waait npm package. It delays until the next "tick" of the event loop, and allows time for that Promise returned from MockedProvider to be fulfilled. After that Promise resolves (or rejects), the component can be checked to ensure it displays the correct information — in this case, "Buck is a poodle".
From https://www.apollographql.com/docs/react/development-testing/testing/#testing-final-state
=> feat: testing final state [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
Decorators are not well stacked – we sometimes need a context in a child decorator
Is:
```jsx
<DecoratorUsingProvider>
<Provider>
<Story />
</Provider>
</DecoratorUsingProvider>
```
Should be:
```jsx
<Provider>
<DecoratorUsingProvider>
<Story />
</DecoratorUsingProvider>
</Provider>
```
Reverse decorators array
=> fix: reverse decorators array [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
When we reverse all the decorators array, we are going against the decorator logic that put every new decorator around the next one.
We need to keep this to make storybook and tests work together.
We still want to stack global decorators first.
```diff
- [...globalDecorators, ...localDecorators]
+ [...localDecorators, ...globalDecorators]
```
As `decorateStory` will stack them.
=> fix: reverse global and local decorators for tests [no issue]

@ornikar/jest-config/test-setup-after-env.js
L'ensemble des erreurs `act` ont été corrigé sur la learner-webapp. On a donc plus besoin de transformer ces erreurs en warnings.
Supprimer le bout de code qui transforme ces erreurs en warnings.
=> feat: act errors are not filtered anymore [no issue]

.eslintignore, @ornikar/browserslist-config/package.json, @ornikar/commitlint-config/package.json, @ornikar/eslint-config-babel-use/package.json, @ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-formatjs/package.json, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config-node/plugins/node.js, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/package.json, @ornikar/eslint-config/plugins/unicorn.js, @ornikar/intl-config/package.json, @ornikar/jest-config-react/package.json, @ornikar/jest-config/package.json, @ornikar/lerna-config/package.json, @ornikar/postcss-config/package.json, @ornikar/prettier-config/package.json, @ornikar/renovate-config/package.json, @ornikar/repo-config-react/package.json, @ornikar/repo-config/package.json, @ornikar/rollup-config/package.json, @ornikar/storybook-config/webpack-configs/base.js, @ornikar/stylelint-config/package.json, @ornikar/webpack-config/package.json, package.json, yarn.lock
While doing another PR (for data-testid), I saw that current config doesnt lint all js files.
add eslintignore, lint "."
=> chore: lint all js files [no issue]

@ornikar/eslint-config-react/rules/react.js, @ornikar/eslint-config-react/tests/Typography.js
=> fix: disable jsx-pascal-case [no issue]

@ornikar/renovate-config/package.json
Allow to merge one by one (or only one)
=> fix(renovate): don't regroup eslint plugins for major updates [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
Found this issue while updating ApolloDecorator.
`decorateStory` returns a function that take an object called context with inside another object called parameters, not parameters directly
=> fix(jest-config-react): pass parameters in context object [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
due to https://github.com/ornikar/shared-configs/pull/429, story name were not passed correctly
create a context object, containing both parameters and name
=> fix(jest-config-react): missing name in context [no issue]

@ornikar/eslint-config-node/README.md, @ornikar/eslint-config-node/module-override.js
In test-setup of components (https://github.com/ornikar/components/blob/master/test-setup.js) it is parsed by babel so it understands esm. We can't rename this file as mjs, because it doesnt currently works well with jest
Add an override-module to be used in components (and other repo)
=> feat(eslint-config-node): add module-override [no issue]

@ornikar/browserslist-config/package.json, @ornikar/commitlint-config/package.json, @ornikar/eslint-config-babel-use/package.json, @ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-formatjs/package.json, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/package.json, @ornikar/intl-config/package.json, @ornikar/jest-config-react/package.json, @ornikar/jest-config/package.json, @ornikar/lerna-config/package.json, @ornikar/postcss-config/package.json, @ornikar/prettier-config/package.json, @ornikar/renovate-config/package.json, @ornikar/repo-config-react/package.json, @ornikar/repo-config/package.json, @ornikar/rollup-config/package.json, @ornikar/stylelint-config/package.json, @ornikar/webpack-config/package.json, package.json
We don't really need 12.16, and one of our app is still in 12.14. We should update, but while we do,
Require 12.13 instead, the first node 12 lts
=> feat: require node 12 fist lts [no issue]

@ornikar/rollup-config/createRollupConfig.js
Before: `.styles-module_IconContainer__LmtH9`
After: `.kitt_IconContainer_LmtH9`
=> smaller and safer
I guess I missed this config when I upgraded a version of rollup postcss plugin ?
=> fix(rollup-config): postcss generate scoped name [no issue]

@ornikar/renovate-config/package.json, @ornikar/rollup-config/createRollupConfig.js
The main issue is that reviewflow automerges majors
- fix to never automerge majors (split groups vs automerge config)
- updated config keys ie `packagePatterns` => `matchPackagePatterns`
- moved rules on automerge first, rules on grouping after
- fixed semanticCommitType for dependencies
- applies yarnDedupeFewer + yarnDedupeHighest to reduce duplicates
=> feat(renovate-config): update config [no issue]

@ornikar/renovate-config/package.json, renovate.json
Too much auto approve + fix schedules
=> fix(renovate-config): only auto approve patch and configs, fix schedules [no issue]

@ornikar/renovate-config/package.json
https://ornikar.atlassian.net/wiki/spaces/A/pages/2067365972/2021-02-02#Discussions
I'm not 100% sure it will work, it might be `team:@ornikar/frontend-architects` ?
https://docs.renovatebot.com/configuration-options/#reviewers
=> feat(renovate-confg): auto request reviews from frontend architects [no issue]

@ornikar/renovate-config/package.json
Current config:
```
{
"matchPackagePatterns": [
"^@ornikar/"
],
"matchUpdateTypes": [
"patch"
],
"labels": [
":ok_hand: code/approved",
":soon: automerge"
],
"reviewers": []
},
{
"matchPackagePatterns": [
"^@ornikar/(.*)-config",
"^@commitlint",
"^eslint"
],
"matchPackageNames": [
"husky",
"prettier",
"yarnhook"
],
"matchUpdateTypes": [
"minor",
"patch"
],
"labels": [
":ok_hand: code/approved",
":soon: automerge"
],
"reviewers": [],
"rebaseStalePrs": false,
"masterIssueApproval": false,
"schedule": [
"after 10am and before 11am every weekday"
]
},
{
"matchPackagePatterns": [
"^@ornikar/"
],
"schedule": [
"after 10am and before 6pm every weekday"
]
},
```
Schedule is defined for `@ornikar/*` packages but not `"masterIssueApproval": false`, we have to check in the renovate issue before …
=> fix(renovate-config): open ornikar prs in schedule [no issue]

.circleci/config.yml, @ornikar/rollup-config/README.md, @ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, @ornikar/rollup-config/rollup-plugin-ignore-browser-only-imports.js, yarn.lock
Update rollup 2 and plugins
Also uses babel/runtime to reduce the size of the generated dist and reuse helpers already imported in other libraries
=> feat(rollup-config): rollup 2 ARCH-901

@ornikar/jest-config-react/package.json, yarn.lock
https://ornikar.atlassian.net/wiki/spaces/A/pages/2067365972/2021-02-02
We want to maintain test dependencies nearer to the latest versions
Update peer dependencies so package depending on `@ornikar/jest-config-react` can be updated
=> feat: update testing-library/react v11 & testing-library/react-hooks to v5 [no issue]

@ornikar/lerna-config/bin/generate-eslintrc-files.js
Fixes issues when eslintrc generator doesnt agree with repo prettier config
Pass config to `prettyEslintConfig` so it use the same config of prettier everywhere
=> fix(lerna-config): eslintrc generator fix prettier config [no issue]

@ornikar/renovate-config/package.json
eslint-config-formatjs is missing in renovate config
=> feat(renovate-config): add missing eslint-config-formatjs [no issue]

@ornikar/jest-config/test-setup-after-env.js, @ornikar/postcss-config/index.js, @ornikar/repo-config-react/createLintStagedConfig.js, @ornikar/rollup-config/createRollupConfig.js, package.json
enable use of `--report-unused-disable-directives` eslint option
=> refactor: eslint report unused disable directives ARCH-1184

@ornikar/lerna-config/bin/generate-eslintrc-files.js
BREAKING CHANGE: requires eslint 7
With the latest eslint-config-typescript with eslint 7, when eslint-config-typescript-react is used eslint-config-typescript also
update lerna config to avoid requiring them both
=> feat(lerna-config): remove @ornikar/eslint-config-typescript when @ornikar/eslint-config-typescript-react is present [no issue]

@ornikar/rollup-config/createRollupConfig.js
I made a mistake when I fixed the concat issue with eslint 7
Use flatMap to flatten the map. Tested with kitt.
=> fix(rollup-config): use flatMap [no issue]

@ornikar/repo-config-react/.svgo.yml
It's the only thing that differs from our config of https://github.com/kristerkari/react-native-svg-transformer/blob/master/index.js#L51-L65
Having the same config avoids running svgo at each build.
https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js#L24-L25
=> fix(repo-config-react): svgo config for react-native compatibility [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
private package are examples or apps. In that case, react is in dependencies, not peerDependencies.
=> fix(@ornikar/lerna-config): support private package with react [no issue]

@ornikar/jest-config/global-mocks.js, @ornikar/jest-config/package.json, yarn.lock
timezone-mock can cause issues and we can still use if for specific tests when we need to change timezone.
Otherwise, it is safer and preferable to use TZ env variable 
```
"test": "TZ='UTC' jest"
```
=> feat: drop timezone-mock in favor of env variable [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
react 17 adds a new jsx transformer that makes importing React useless.
=> feat(lerna-config): support react 17 [no issue]

@ornikar/rollup-config/createRollupConfig.js
Support for examples to be in monorepo librairies, packages that don't need to be built
Related PR: https://github.com/ornikar/shared-configs/pull/542
=> fix(rollup-config): do not build private packages [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
We can now wait for something before snapshoting a story
Example:
=> feat: add waitFor in stories mock [no issue]

@ornikar/repo-config/createLintStagedConfig.js
Like renovate ( https://github.com/ornikar/shared-configs/blob/master/@ornikar/renovate-config/package.json#L20-L22 ) and what we do manually ( https://ornikar.atlassian.net/wiki/spaces/MB2C/pages/2949087586/Version+dependencies+management+-+WIP )
=> fix(repo-config): run yarn dedupe fewer, like renovate does [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
for example, expo/tsconfig.base for expo app
=> fix(lerna-config): allow apps and examples to extends from something else [no issue]

@ornikar/storybook-config/index.js
now that we don't have index.ts/view.ts the stories should be suffixed by the name of the file
=> feat(storybook-config): add *.stories.{ts,tsx} [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx
`wrapper` doesn't render what is wrapped in the snapshot
=> fix(jest-config-react-native): use wrapper option in storybook mock [no issue]

@ornikar/renovate-config/package.json
ornikar eslint configs used to be in shared-configs, this is no longer the case and title is misleading
=> fix(renovate-confg): change eslint configs group as no longer in shared-configs [no issue]

@ornikar/intl-config/.eslintrc.json, @ornikar/renovate-config/.eslintrc.json, @ornikar/repo-config-react/.eslintrc.json, @ornikar/repo-config/.eslintrc.json, package.json
- fix legacy eslint-config-node which was replaced some time ago by eslint-config/node
- remove ext in eslint command which is no longer necessary with eslint 7
=> chore: fix eslint config [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
Replaced `__DEV__` by `process.env.NODE_ENV !== 'production'` instead
Reduce the number of dist files and the size of published package.
BREAKING CHANGE: no more dev builds
=> feat(rollup-config): stop building dev version [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
a thing from my past
setting rootDirs is not necessary at all
related to https://github.com/christophehurpeau/pob/commit/11cea8d6fed56ad4405044e10f906d08e8ca3c02#diff-ce4ff68de1e531b53ccf71332f8bd1368367c28f13147f85e27a400f4c342c50
=> fix(lerna-config): dont add dep path in rootDirs [no issue]

@ornikar/lerna-config/bin/generate-eslintrc-files.js, @ornikar/lerna-config/bin/generate-tsconfig-files.js
We don't want tsconfig nor eslint config files in packages that don't have source files
Example:
- https://github.com/ornikar/kitt/tree/master/%40ornikar/geomanist-font
- https://github.com/ornikar/shared-apps/tree/main/%40ornikar/webapp-tools
Tested on shared-apps
=> fix(lerna-config): support empty entries in generators [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
While updating apollo in a webapp, I found the wait(0) didn't work anymore and `wait(0).then(() => wait(0))` worked.
However, it seemed stranged to make this change in this shared config repository, specially when not all repo uses apollo
let the app add parameters globally via test-setup so that `wait(0)` can be configured there, and even add conditions based on parameters passed.
Example
> test-setup.ts
```
addParameters({
jest: {
waitFor: () => wait(0).then(() => wait(0)),
},
});
```
=> feat(jest-config-react): remove random wait, add global addParameters [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
Building libs for react-native requires to target specific extensions and should tree shake using Platform.OS
Add plugin babel-plugin-react-native
=> feat(rollup-config): add platform os support with specific builds [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
This pattern can be used in tests/stories
Add self to paths for tsconfig.build.json
=> fix(lerna-config): allow library to self import [no issue]

@ornikar/rollup-config/createRollupConfig.js
`!__DEV__` is currently replaced by rollup to `!process.env.NODE_ENV !== "production"`
What we really want is `!(process.env.NODE_ENV !== "production")`
We should probably use babel to replace this as it should be more safer, but this is for another PR
Related:
https://github.com/christophehurpeau/pob/commit/1d9296dd658ae741337302eefde237d402ee35bd
https://github.com/christophehurpeau/pob/commit/1dc4aa94b86546497249b725b0a75ce8d2f352a3
=> fix(rollup-config): fix `!__DEV__` [no issue]

@ornikar/intl-config/generate-translations.js
… wide
`generate-translations` only threw an error if there was a duplicate inside a section
Now it should throw if there is a duplicate inside the whole project
=> feat: check translations duplicates project wide and not only section wide [no issue]

@ornikar/jest-config-react/jest-preset.js
now that we need to use web version of styled-components, we need to use the native version in jest (for metro, it's automatic)
=> feat(jest-config-react): add styled-components module name mapper [no issue]

@ornikar/jest-config-react/jest-preset.js
In monorepos with web and native code, we want to generate both native and web snapshots from native stories wo we need to mock storybook/react-native in the same way that storybook/react is mocked
We use modulenamemapper in jest config to map @storybook/react-native to the mock implem of storybook/react
=> feat(jest-config-react): mock @storybook/react-native [no issue]

@ornikar/jest-config/package.json, @ornikar/jest-config/test-setup-after-env.js, yarn.lock
[jest-circus](), the default for jest 27 but already used in creact-react-app (https://github.com/facebook/create-react-app/blob/54ad467598214927bab38e163ff520063c3a00df/packages/react-scripts/scripts/utils/createJestConfig.js#L42), doesnt support jasmine api anymore
I tried fixing it, but it's even better to use a lib that does that.
=> fix(jest-config): support next-gen jest-circus runner [no issue]

@ornikar/jest-config-react-native/jest-preset.js, @ornikar/jest-config-react-native/svg-transformer-inline.js, @ornikar/jest-config-react-native/svg-transformer.js
librairies and apps currently doesnt have the same loader for svg.
- webpack libraries (kitt/components): svg-react-loader
- rollup librairies: babel-plugin-inline-react-svg
- webpack with create-react-app: @svgr/webpack
- metro: @svgr/core via @ornikar/react-native-svg-transformer
- use `exportType: name` config for svgr in `@ornikar/react-native-svg-transformer` to support app svg import format (commit: https://github.com/ornikar/react-native-svg-transformer/commit/9aefd6285f3673c902f78a73bf7a0e0f530429fa)
- configure a transformer in jest-config-react-native preset to support the new format while still having a fallback for libaries. Apps like instructors-app will need to make changes to work, so this is a breaking change.
We should use svgr everywhere in the same way: webpack config …
=> feat(jest-config-react-native): support svg with svgr named loader CME-229

@ornikar/jest-config-react-native/jest-preset.js
…[no issue]
When we use addDecorator in a monorepo shared directory context (jest or Storybook config), we want to use always the same one
Add a moduleNameMapper for jest
=> feat: add storybook react module mapper in jest react native preset [no issue]

@ornikar/storybook-config/addon/webpackFinal.js, @ornikar/webpack-config/processEnv.js, @ornikar/webpack-config/reactNativeWeb.js
Allow react-native-web config to be used in craco config, not only storybook config.
=> feat(webpack-config): move react-native-web config from storybook and fix for process.browser [no issue]

@ornikar/storybook-config/theme.js
fix missing theme prop `textMutedColor` (finally getting rid of that warning) and update colors to match late-ocean
=> feat(storybook-config): update theme late-ocean [no issue]

@ornikar/rollup-config/__snapshots__/createRollupConfig.test.js.snap, @ornikar/rollup-config/createRollupConfig.js
`@babel/runtime/helpers/objectSpread2` was not used resulting in a lot of duplicated helpers in code generated by rollup
Make sure we use recent `@babel/runtime` version in our lib and pass version in plugin
=> fix(rollup-config): spread runtime helper [no issue]

@ornikar/webpack-config/reactNativeWeb.js
styled-components and react-native-web were babelified in webpack config (used by both storybook and applications with craco)
we saw that by testing in sherwood-webapp.
Exclude these two libraries
=> fix(webpack-config): fix react-native-web and styled-components/native babelified when not needed [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
if you used clean:cache, add clean:cache:on-dependencies-changes script.
clean:cache should clean all cache, but we dont want to clean everything by default when dependencies changes.
For example, jest cache can still be present
https://ornikar.slack.com/archives/CC9F4CTDH/p1647962343116919
=> chore(repo-config): replace clean:cache by clean:cache:on-dependencies-changes [no issue]

@ornikar/renovate-config/package.json
Components and kitt PRs will automaticly set reviewer to @ornikar/frontend-shared-components-maintainers  instead of  @ornikar/frontend-architects 
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3204677657/Shared+React+Components+2022-04-26
=> feat(renovate-config): team frontend-shared-components-maintainers [no issue]

@ornikar/jest-config/bin/test-coverage.sh
BREAKING CHANGE: jest collect coverage output directory needs to be `coverage`
=> fix(ornikar-test-coverage): jest collect coverage output path [no issue]

@ornikar/intl-config/package.json, yarn.lock
this option is only available since 7.13.0 : https://babeljs.io/docs/en/options#browserslistconfigfile
Note: this is not a breaking change as past versions crashed without this babel version
=> fix(intl-config): fix peer dep requires min babel core ^7.13.0 [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
- With yarn berry, we will run the install script on every jobs
- husky is not necessary to use on CI. Even for jobs that commit stuff, they should not rely on lint-staged to fix formatting.
skip husky install on CI using `process.env.CI`
This might cause issues on monorepo libraries when releasing
=> feat(repo-config): skip husky install on ci [no issue]

@ornikar/jest-config-react-native/web/jest-preset.js
Dans le cadre de l'utilisation de `react-native-svg` dans le web, et surtout dans les stories jest, on souhaite mapper les improts vers `react-native-svg` vers `react-native-svg-web` pour que le rendu snapshots des stories fonctionnent correctement 👍
=> feat(jest-config-react-native): support for react-native-svg-web ELN-3031

@ornikar/repo-config/createLintStagedConfig.js
Followup of https://github.com/ornikar/shared-configs/pull/764
- no longer specify arguments for `.env*` to prettier in lint-staged
- add prettier for `*.env`
=> fix(repo-config): fix prettier env files [no issue]

@ornikar/repo-config/createLintStagedConfig.js, @ornikar/repo-config/lib/postinstall/install-husky.js
Currently, `tsc` is ran on every pre-commit, after lint-staged.
tsc can be slow on big projects.
CI checks tsc too.
Using lint-staged to run tsc will:
- run tsc in parallel with the other tasks (eslint/yarn etc)
- only run tsc when ts/tsx file changed
=> feat(repo-config): only run tsc on pre-commit when ts file changed [no issue]

.github/workflows/release-alert.yml
En lien avec https://github.com/ornikar/.github/pull/7/files
On ne peut pas tester les `reusable workflows` avec `act`. Obligé de "tester en prod"
On utilise le workflow générique.
=> feat: use generic release alert workflow instead of local one

@ornikar/repo-config/bin/ornikar-lint-staged.mjs
https://ornikar.slack.com/archives/CC9F4CTDH/p1668002640656459
Husky was failing silently during the precommit phase. ornikar-lint-staged was catching an error (here I had a dependency mismatch between repo-config & lerna-config) but did not log it in the console.
Add a console.log(error).
=> feat: log errors during ornikar-lint-staged command [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
The cleanup function in testing-library/react should be called automaticly. However it is never called, resulting in performance issues (memory leaks ?) and sometimes invalid tests.
testing-library registers cleanup via afterEach, which is not available in test-setup, only on test-setup-after-env
We import testing-library in test-setup via storybook mocks, as we add decorators/parameters
The solution is to move the import in the `storiesOf` which should be called only once on each story test file. This way, in the test-setup phase, testing-library is no longer imported, and afterEach will be available when `storiesOf` is called
This also has another benefits: for tests not using testing-library, it will never be imported.
Perf test using hyperfine:
Impact on time on react (components / …
=> fix(jest-config-react): fix testing library cleanup ECF-58

@ornikar/jest-config/jest-preset.js, @ornikar/jest-config/test-shim.js
mocking requestAnimationFrame is no longer necessary
and has issues linked to setTimeout / jest timeouts
Tested on kitt and learner-apps.
=> fix: remove test shim [no issue]

@ornikar/jest-config-react-native/package.json, @ornikar/jest-config-react-native/transformers/babel-transformer-node-modules.js, yarn.lock
Following the migration to Jest 27 (#812), some config needs to be updated.
- Add missing the peer dep `jest` in the `jest-config-react-native/package.json` file
- Fix the import of `babel-jest` (relative issue => https://app.circleci.com/pipelines/github/ornikar/insurance-selfcare-webapp/5311/workflows/8766ebcc-8e31-4eb6-82a0-2f3826dd3a46/jobs/32440)
=> fix: update config for Jest 27 ONK-4620

@ornikar/renovate-config/package.json
For most cases, let reviewers set in repository's renovate configuration as reviewers, except for orbs
that should be done by at least one member in the foundation working group
=> feat(renovate-config): update reviewers for q1 2023 [no issue]

@ornikar/jest-config/test-setup-after-env.js
Des warnings non justifiés apparaissent avec la MAJ de jest 27
On les ignore jusqu'à la MAJ de React 18, qui les enlèvera tout seul
=> feat: ignore act warnings from rtl [no issue]

@ornikar/jest-config-react/transformers/svg-transformer-inline.js, @ornikar/jest-config-react/transformers/svg-transformer.js
jest 29 requires to use `code` as return to the process() function
=> fix: update transformers for jest 29 [no issue]

@ornikar/storybook-config/index.js
As we migrate to native-base, and for repositories with native-apps only, we don't need to process css with postcss.
Add option to disable addon
=> feat(storybook-config): add option to disable postcss [no issue]

@ornikar/intl-config/extract-translations.js
Currently if we edit an fr-FR.json in our IDE and save it (or have autosave enabled), this will add a newline at the end and ci will fail as it does not match content generated by script.
Add a newline to match what we ask of the IDE
=> fix(intl-config): add newline eof to match editorconfig [no issue]

@ornikar/storybook-config/addon/webpackFinal.js, @ornikar/storybook-config/index.js, @ornikar/storybook-config/webpack-configs/cssModulesRule.js
cra addon is used only in sherwood-webapp.
While testing, it was broken: postcss rule should not be applied in the same way
Fix config for CRA addon.
=> fix(storybook-config): usage with cra addon ECF-228

@ornikar/webpack-config/processEnv.js
`process.version` is used in https://github.com/auth0/node-jsonwebtoken/blob/master/lib/asymmetricKeyDetailsSupported.js
=> fix(webpack-config): add define process.version for jsonwebtoken [no issue]

@ornikar/webpack-config/linaria.js
BREAKING CHANGE: instead of @linaria/webpack-loader dependency, install @linaria/webpack5-loader
Fix a security issue present in @linaria/webpack4-loader
@linaria/webpack-loader install both @linaria/webpack4-loader and @linaria/webpack5-loader
=> feat!: use linaria webpack5 loader [no issue]

@ornikar/jest-config-react-native/jest-preset.js, @ornikar/jest-config-react-native/ornikar-react-native-env.js, @ornikar/jest-config-react-native/web/jest-preset.js
Currently importing ornikar libraries with `exports` configuration fails because of missing react-native export.
react-native configuration of jest only allows `react-native` condition, but it is the same one that the one metro is experimenting with. We need to differenciate both of them, to precompile our libraries for the target properly.
This configuration allows this kind of exports:
=> feat(jest-config-react-native): add testEnvironment config for native [no issue]

@ornikar/jest-config-react/test-setup-after-env.js
react-native web deprecated multiples props, but native-base is either settings these props or not supporting the same as rnw so we need to silence the warnings.
https://github.com/necolas/react-native-web/pull/2377/
=> feat: silence warnings linked to react-native-web 19 INS-2508

@ornikar/lerna-config/bin/generate-tsconfig-files.mjs
Using baseurl causes issues for distribution files, as seen multiple times like https://github.com/ornikar/shared-apps/pull/731.
stop using baseUrl for libraries and use relative imports
=> fix(lerna-config): tsconfig generation without baseurl [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.mjs
tsc has cache enabled. Each package references other packages needed (same as dependencies) and tsc only build once and reuse built declarations.
However, we don't need to build declaration if the package is not reused as a dependency
=> feat(lerna-config): disable emit declaration cache when tsconfig has no references [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
Very simple tests in eslint-configs that does not requires jest.
Use of https://nodejs.org/api/test.html available since node 18 (we're not there yet but very very close)
=> feat(repo-config): add support for simple node test runner prepush hook [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
When testing-library is loaded, it checks for an `afterAll` to add the cleanup step.
But when we load decorators in the test-setup, as it's in early initialization, jest has not yet initialized the hooks. So, no cleanup
I made a fix that obsiously did not work properly: https://github.com/ornikar/shared-configs/pull/804 maybe because jest parses `require`s ?
Example on react-native tests (`yarn test:native --no-cache`):
BEFORE: 48.661s
AFTER: 35.993s
Example on web tests (`yarn test:web --no-cache`):
BEFORE: 203.242s
AFTER: 164.08s
=> fix: storybook mocks should be in testSetupAfterEnv to make sure testing-library is cleanup properly [no issue]

@ornikar/babel-preset-kitt-universal/lib/__tests_fixtures__/web-simple-tag.js, @ornikar/babel-preset-kitt-universal/lib/__tests_fixtures__/web-with-linaria.js, @ornikar/babel-preset-kitt-universal/lib/__tests_fixtures__/web-with-react-refresh-and-linaria.js, @ornikar/babel-preset-kitt-universal/lib/__tests_fixtures__/web-with-react-refresh.js, @ornikar/babel-preset-kitt-universal/lib/index.js
We deprecated styled-components and mostly no longer use it
Keep it while we still use it but disabled by default.
=> feat(babel-preset-kitt-universal)!: disable styled-components plugins by default [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
Cleanup is not ran just after tests but after tasks are finished
However with snapshots and stories, we want to unmount as soon as possible to avoid other animations and effects to happen and fail our tests due to not using `act`.
use unmount
=> fix: fix unmount on stories tests [no issue]

@ornikar/intl-config/extract-translations.js
The extract-translations file contains a filename check to avoid duplicates. The absolute path is checked. However, if this has a dot before the file extension, the check is not correct. 
Use relative filename path instead.
=> fix: get relative path from extract translations file [no issue]

@ornikar/repo-config/bin/ornikar-repo-config-postinstall.js, @ornikar/repo-config/lib/postinstall/install-husky.js
yarn legacy is not supported in lint-staged already and we migrated to yarn berry all our repositories a long time ago.
cleanup postinstall script.
=> refactor(repo-config): drop yarn legacy and npm support [no issue]

@ornikar/jest-config-react-native/customTransforms.js
Update to expo 49
`@react-native/virtualized-lists` is not compatible with sucrase, throws this error: "TypeError: Cannot redefine property: state"
Add to libraries going through babel instead of sucrase
=> fix(jest-config-react-native): add library not compatible with sucrase for expo 49 [no issue]

@ornikar/webpack-config/workspaceAliases.js
Add support for HMR with entries in monorepos.
Examples: `@ornikar/kitt-icons/phosphor` ; `@ornikar/runtime-app/sentry`.
=> feat(webpack-config): add support for entries [no issue]

@ornikar/jest-config-react-native/customTransforms.js, @ornikar/jest-config-react-native/jest-preset.js, @ornikar/jest-config-react-native/transformers/babel-transformer-ornikar-packages.js
The new rollup config created an issue with jest where the reanimated plugin wasn't applied on our packages.
- Added a custom transform to apply the reanimated plugin on our packages
- Excluded our packages from the transformIgnorePatterns
=> feat: add reanimated transform for ornikar packages on jest [no issue]

@ornikar/jest-config-react-native/customTransforms.js
This transform was added to pass the reanimated plugin on the files created by rollup (since we don't pass the reanimated plugin on the file when rollup does the transform)
The regex was too permissive and also included files from the node_modules of our packages.
Changed the regex to only include files in the dist folder of our packages
=> fix: ornikar package custom transform [no issue]

@ornikar/jest-config/bin/ornikar-run-jest.mjs
Avec node 18, on forçait l'usage de node 21 pour executer les tests. Node 20 inclut le correctif de fuite mémoire, ce check n'est donc plus nécessaire. De plus, on va préférer utiliser la LTS de node.
=> feat: remove node 21 usage on test [no issue]

@ornikar/jest-config-react-native/jest-preset.js, @ornikar/jest-config/jest-preset.js
We want to unify our `jest` configurations.
Extract configuration parts from insurance and education repositories that appear to be the same.
=> feat: unify `jest` configs between insurance and education repositories [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
ne pas ajouter l'installation des dépendences iOS si jamais le dossier iOS est dans le gitIgnore (expo managed)
=> feat: do not add pod-install if expo managed project [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
`/ios/` était trop flex, ça supprimait également le script pod install dans la learner-apps car elle contient un. `/ios/Pods` dans son gitignore
- testé sur learner-apps et INA (branche expo prebuild)
=> fix: husky pod install rules [no issue]
