ornikar/shared-configs

README.md, package.json
https://eslint.org/docs/developer-guide/shareable-configs
https://github.com/eslint/eslint/commit/936bc174aa67f72d5ffee32f932f3180f3ffca22#diff-33bbe98f532eb757e2789f1a3549c9caR126
=> chore: move to ornikar scope

@ornikar/eslint-config/babel.js, @ornikar/eslint-config/index.js, @ornikar/eslint-config/package.json, @ornikar/eslint-config/plugins/filenames.js, yarn.lock
BREAKING CHANGE: requires eslint-plugin-filenames
=> feat: eslint plugin filenames

@ornikar/eslint-config/package.json, package.json, yarn.lock
BREAKING CHANGES: eslint ^5.3, eslint-plugin-prettier ^2.6.2, eslint-plugin-unicorn ^5.0.0, prettier ^1.14.2
A merger apres la mise a jour des dependences d'airbnb: https://github.com/airbnb/javascript/issues/1834
=> feat(eslint config): update dependencies

@ornikar/browserslist-config/degraded-support.js, @ornikar/browserslist-config/full-support.js, @ornikar/eslint-config/package.json, @ornikar/stylelint-config/package.json, package.json, yarn.lock
BREAKING CHANGE: prettier@^1.14.3, eslint-plugin-prettier@^3.0.0
=> chore: update prettier config

@ornikar/eslint-config/package.json, @ornikar/eslint-config/plugins/unicorn.js, @ornikar/eslint-config/rules/react.js, yarn.lock
BREAKING CHANGES: eslint-plugin-unicorn@^6.0.1, prettier@^1.14.3, eslint@^5.7.0, react/sort-prop-types enabled
=> feat: update eslint config

@ornikar/postcss-config/package.json, @ornikar/stylelint-config/package.json, yarn.lock
BREAKING CHANGE: prettier@^1.14.3, stylelint@^9.6.0
=> feat: update postcss config

@ornikar/renovate-config/package.json
Regroupe les mises à jour de eslint en une seule PR et l'auto merge si tout les tests passent.
=> feat: group eslint updates [no issue]

@ornikar/eslint-config-babel/package.json
=> chore: remove babel-eslint in devDependencies [no issue]

@ornikar/renovate-config/package.json
J'ai regardé la doc, j'ai rien trouvé de concluant pour obtenir le résultat que je souhaitais, sans casser la possibilité de rebase automatiquement.
Du coup je pense que c'est mieux de revert à la config précedente.
=> fix: allow rebasing in PRs [no issue]

@ornikar/renovate-config/package.json, renovate.json
Pour pouvoir tester les checkbox.
J'ai aussi changé le renovate.json à la racine du projet, la config me semblait pas pertinente ?
=> feat: rebase in schedule [no issue]

@ornikar/renovate-config/package.json
https://github.com/renovatebot/renovate/pull/3322
use yarn-deduplicate, like https://www.npmjs.com/package/yarn-update-lock
=> feat(renovate-config): enable dedupe [no issue]

@ornikar/renovate-config/package.json
https://ornikar.atlassian.net/browse/ONK-3276
Pour tester : https://codepen.io/antonlydike/full/KgygpA
=> feat: update schedule to match platform days ONK-3276

@ornikar/jest-config-react/__mocks__/@storybook/react.js
https://github.com/storybooks/storybook/blob/next/lib/client-api/src/client_api.js#L34
Pass through decorators in stories
We need this in sherwood-react because we can use decorators to mock results or pass context on multiple stories
=> feat(jest-config-react): support decorators [no issue]

@ornikar/jest-config/global-mocks.js, @ornikar/jest-config/jest-preset.js, @ornikar/jest-config/package.json, yarn.lock
besoin dans https://github.com/ornikar/sherwood-react/pull/55/files
meme chose que fait dans learner-app
=> feat: add timezone-mock in jest config [no issue]

@ornikar/eslint-config-node/index.js, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config/plugins/unicorn.js
J'ai quand même mis toutes les règles. Je pense pas qu'il y en ai qui pose problème avec l'existant.
=> fix: add new unicorn rules [no issue]

@ornikar/eslint-config-react/index.js
j'ai hésité entre warn et error, mais autant explicitement ignorer l'erreur si on l'a lu et qu'on veut passer outre ?
=> feat: enable react-hooks/exhaustive-deps [no issue]

.circleci/config.yml, package.json, yarn.lock
this will allow renovate to show changelogs
=> ci: enable github releases [no issue]

@ornikar/jest-config/package.json
BREAKING CHANGE: #145 introduced a breaking change of jest 24
=> fix: jest 24 breaking change [no issue]

@ornikar/jest-config-react/__mocks__/storybook-react-router.js, @ornikar/jest-config-react/jest-preset.js
Pour learner-app, on utilise storybook-react-router
Implémentation du mock
=> feat: support storybook-react-router [no issue]

@ornikar/jest-config-react/jest-preset.js, @ornikar/jest-config/jest-preset.js
pour learner-app, on va avoir typescript et js qui coexiste
Permettre d'ecrire des tests et stories dans les 2 langages
=> feat: allow both js and ts tests [no issue]

@ornikar/renovate-config/package.json
Permet d'auto merge certaines prs de renovate
[JIRA issue: ONK-3277](https://ornikar.atlassian.net/browse/ONK-3277)
=> chore: renovate-config ONK-3277

@ornikar/renovate-config/package.json
Ajoute le label automerge pour faciliter le process renovate.
Utilise le label code/approved pour indiquer que la pr n'a pas besoin de review.
=> feat: renovate labels config [no issue]

@ornikar/renovate-config/package.json
=> feat: renovate add missing label automerge [no issue]

@ornikar/browserslist-config/degraded-support.js, @ornikar/browserslist-config/full-support.js, @ornikar/eslint-config-typescript/index.js, @ornikar/eslint-config/rules/best-practices.js, @ornikar/eslint-config/rules/style.js, @ornikar/jest-config-react/__mocks__/@storybook/addon-knobs.js, @ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/__mocks__/storybook-react-router.js, @ornikar/jest-config-react/jest-preset.js, @ornikar/jest-config/test-setup-after-env.js, @ornikar/jest-config/test-shim.js, @ornikar/postcss-config/index.js, @ornikar/prettier-config/index.js, @ornikar/prettier-config/package.json, @ornikar/stylelint-config/index.js, package.json
Aujourd'hui nos configurations prettier sont faites dans les package.json de chacun des projets.
Cette PR permettra d'uniformiser ces règles
Créer un configuration partagée de prettier.
J'ai mis une `printwidth` de 120. Ça vaut le coup de faire un vote sur teamfront ?
=> feat: prettier config [no issue]

@ornikar/renovate-config/package.json
Les majeurs doivent faire l'objet d'attention particulières
Cela permet de les valider dans la master issue avant l'ouverture d'une PR
=> feat: enable master issue approval for majors [no issue]

@ornikar/eslint-config-typescript/index.js
=> fix: explicit function return type is not disabled [no issue]

@ornikar/eslint-config-typescript/index.js
=> fix: remove duplicate rule [no issue]

@ornikar/eslint-config-typescript/index.js
Désolé, normalement ça devrait être bon 🙄 
=> fix: rule should be warning [no issue]

@ornikar/eslint-config-typescript/index.js
=> fix: rule should be warn [no issue]

@ornikar/jest-config/jest-preset.js
Fix les tests sur https://github.com/ornikar/kitt/pull/642 et evite de remettre cette config sur chaque repo
[JIRA issue: ONK-3913](https://ornikar.atlassian.net/browse/ONK-3913)
=> fix: add module directories for lerna and module paths for non lerna projects ONK-3913

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
Reverts ornikar/shared-configs#245
=> fix: bring back rollup plugin ignore for node and fix config ONK-3913

@ornikar/renovate-config/package.json
On ne fait plus de renovate aux plateforme days
Permet d'ouvrir les prs au besoin
=> feat: renovate default masterIssueApproval [no issue]

@ornikar/renovate-config/package.json
On a trop de builds circleci du à une release de plusieurs pacakges venant de components
- Groupement des releases
- Création de la PR à la demande seulement
=> feat(renovate-config): group ornikar components [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/storybook-config/webpack-configs/lib.js
Permet de s'assurer qu'on a les meme noms de classe sur storybook et pour la version buildé.
=> fix: use same localIdentName [no issue]

@ornikar/jest-config-react/fileTransform.js, @ornikar/jest-config-react/jest-preset.js
Cette PR introduit un mock de svg qui n'est pas du tout bon: https://github.com/ornikar/shared-configs/pull/244 car il est fait pour les css modules.
Implementation du bon mock
=> fix: svg transform [no issue]

@ornikar/jest-config/jest-preset.js
Allow to add jest tests in config and script directories.
Theses tests will always be in js
=> feat(jest-config): allow to add tests in config and scripts directories [no issue]

@ornikar/storybook-config/package.json, yarn.lock
=> chore: update storybook-config to 5.2.6 [no issue]

@ornikar/storybook-config/webpack-configs/app.js, @ornikar/storybook-config/webpack-configs/base.js, @ornikar/storybook-config/webpack-configs/lib.js
Permet d'utiliser la config partagée dans les apps aussi
=> feat: add app storybook config [no issue]

@ornikar/eslint-config/plugins/unicorn.js
Too much errors and not always relevant
=> fix: disable unicorn/consistent-function-scoping [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
We can't commit empty test suites, this allows it.
=> feat: add ignore on emtpy test suites [no issue]

@ornikar/intl-config/generate-translations.js
`generate-translations` script was generating translations from test files
=> feat: generate translations ignore tests [no issue]

@ornikar/jest-config/package.json, @ornikar/jest-config/test-shim.js, yarn.lock
=> feat: add polyfill for plural rules [no issue]

@ornikar/jest-config/test-setup-after-env.js
on a des erreurs qui sont des warnings qu'on ne peut aujourdhui pas fixer
=> feat: ignore update act warning [no issue]

@ornikar/intl-config/generate-translations.js, @ornikar/intl-config/package.json, yarn.lock
=> feat: sort keys [no issue]

@ornikar/stylelint-config/index.js
We want to blacklist certain css properties
[JIRA issue: ONK-4162](https://ornikar.atlassian.net/browse/ONK-4162)
=> feat: add blacklisted properties ONK-4162

@ornikar/jest-config-react/test-setup.js
Portal should be mocked as we need to see its content on our snapshots 🌤️ 
see https://github.com/ornikar/sherwood-webapp/pull/454#discussion_r411196520
Mock `createPortal` to make it return its element directly
[JIRA issue: ONK-4263](https://ornikar.atlassian.net/browse/ONK-4263)
=> feat: jest mock portal for testing library ONK-4263

@ornikar/jest-config-react/__mocks__/@storybook/react.js, @ornikar/jest-config-react/jest-preset.js, @ornikar/jest-config-react/package.json, @ornikar/jest-config-react/test-setup.js, yarn.lock
We now use react testing library as default snapshot provider and test maker.
➡️  We don't want to use enzyme anymore
Remove Enzyme ✂️ 
[JIRA issue: ONK-4323](https://ornikar.atlassian.net/browse/ONK-4323)
=> feat(jest-config-react): remove enzyme ONK-4323

@ornikar/jest-config/package.json, yarn.lock
Reverts ornikar/shared-configs#347
=> revert: fix(deps): update dependency chalk to v4 [no issue]

@ornikar/repo-config-react/package.json, @ornikar/repo-config/package.json, yarn.lock
Reverts ornikar/shared-configs#346
=> revert: fix(deps): update dependency cross-env to v7 [no issue]

.circleci/config.yml, @ornikar/browserslist-config/package.json, @ornikar/commitlint-config/package.json, @ornikar/eslint-config-babel-use/package.json, @ornikar/eslint-config-babel/package.json, @ornikar/eslint-config-formatjs/package.json, @ornikar/eslint-config-node/package.json, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config-typescript-react/package.json, @ornikar/eslint-config-typescript/package.json, @ornikar/eslint-config/package.json, @ornikar/intl-config/package.json, @ornikar/jest-config-react/package.json, @ornikar/jest-config/package.json, @ornikar/lerna-config/package.json, @ornikar/postcss-config/package.json, @ornikar/prettier-config/package.json, @ornikar/renovate-config/package.json, @ornikar/repo-config-react/package.json, @ornikar/repo-config/package.json, @ornikar/rollup-config/package.json, @ornikar/stylelint-config/package.json, @ornikar/webpack-config/package.json
Update required node version to LTS (12.16.2)
- node version (08a16ee1c4741c5e4760d104eebed17e8115ae51)
=> feat: update node version to 12 [no issue]

@ornikar/eslint-config/package.json, @ornikar/prettier-config/package.json, @ornikar/stylelint-config/package.json
- prettier version (4a4cdadd1d64d69222c5b8abb429e508567cb1e4)
=> feat: require prettier version to new major [no issue]

@ornikar/jest-config/package.json, yarn.lock
Reverts ornikar/shared-configs#350
=> fix: update dependency chalk to v4 [no issue]

@ornikar/eslint-config-react/rules/react.js
https://github.com/ornikar/kitt/pull/740#discussion_r412729092
=> fix(eslint-config-react): react/sort-comp rule static-variables [no issue]

@ornikar/repo-config/package.json, package.json, yarn.lock
Reverts ornikar/shared-configs#362
=> revert: chore(deps): update dependency lint-staged to v10 [no issue]

.circleci/config.yml, @ornikar/eslint-config-babel-use/package.json, @ornikar/eslint-config-react/package.json, @ornikar/eslint-config/package.json, @ornikar/storybook-config/package.json, @ornikar/stylelint-config/package.json, scripts/check-packagejson.js, yarn.lock
Some peer dependencies are not right
- add yarn check in ci to check peer deps
- simplify ci with executor
- some peer dependencies changed (b3bc48ce4cb8b999223e7b5740eb2c58d66db6b8)
=> refactor: checks [no issue]

@ornikar/renovate-config/package.json
Permet a renovate de mettre a jour les peerdependency en changeant la version par la nouvelle version majeur.
Nécessite toujours que celui qui merge ajoute le breaking change.
=> feat(renovate-config): configure rangeStrategy for majors [no issue]

@ornikar/renovate-config/package.json
https://github.com/renovatebot/renovate/issues/6423
=> feat(renovate-config): remove pr body for reviewflow [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
=> refactor: remove unused waitFor [no issue]

@ornikar/jest-config/global-mocks.js, @ornikar/jest-config/package.json, yarn.lock
https://ornikar.slack.com/archives/GC9F4CTDH/p1592468723002800
Testé sur learner-webapp.
=> fix: use mockdate [no issue]

@ornikar/jest-config-react/__mocks__/@storybook/react.js
initial render should be wrapped in `act` : [**DOC** ](https://reactjs.org/docs/test-utils.html#act)
Wrap initial render in `act`
=> feat: wrap initial render in act [no issue]

@ornikar/renovate-config/package.json
=> feat(renovate): add missing ornikar components [no issue]

@ornikar/eslint-config/graphql.js, @ornikar/eslint-config/rules/style.js
=> feat(eslint-config): allow underscore dangle for __typename field [no issue]

@ornikar/eslint-config-babel-use/tests/.eslintrc.json, @ornikar/eslint-config-babel-use/tests/CustomError.js
=> test: add tests for Custom Errors for rule conflicting with unicorn [no issue]

@ornikar/eslint-config/rules/code-quality.js
=> feat(eslint-config): remove complexity rule [no issue]

@ornikar/stylelint-config/examples/base.css, @ornikar/stylelint-config/examples/modules.css, @ornikar/stylelint-config/index.js
https://ornikar.slack.com/archives/GC9F4CTDH/p1599214580019100 +
https://ornikar.slack.com/archives/GC9F4CTDH/p1599220739024600
=> fix(stylelint-config): allow composes to have any case, allow font-family with inherit value [no issue]

@ornikar/stylelint-config/index.js
Sorry, we also have a few inherit for font-size
=> fix: also allow inherit font-size [no issue]

@ornikar/renovate-config/package.json
skip ci prevent commits from ending up in devenv.
- change schedule, preventing production deployment during the night (could result in breaks if something is wrong in the infra)
- diable skip ci : https://github.com/christophehurpeau/reviewflow/pull/120
=> feat: change renovate schedule [no issue]

@ornikar/lerna-config/generate-tsconfig-files.js
We don't need to create graph, we only need the location and name of the packages. It also simplifies code.
=> fix(lerna-config): fix dont create unecessary graph [no issue]

@ornikar/eslint-config-react/react-native.js
=> fix(eslint-config-react): react-native extends . [no issue]

.gitignore, .vscode/extensions.json, .vscode/settings.json
=> chore: add vscode config [no issue]

@ornikar/browserslist-config/.eslintrc.json, @ornikar/commitlint-config/.eslintrc.json, @ornikar/jest-config-react/.eslintrc.json, @ornikar/jest-config/.eslintrc.json, @ornikar/jest-config/test-setup-after-env.js, @ornikar/lerna-config/.eslintrc.json, @ornikar/lerna-config/bin/generate-eslintrc-files.js, @ornikar/lerna-config/bin/generate-tsconfig-files.js, @ornikar/postcss-config/.eslintrc.json, @ornikar/prettier-config/.eslintrc.json, @ornikar/rollup-config/.eslintrc.json, @ornikar/rollup-config/createRollupConfig.js, @ornikar/storybook-config/.eslintrc.json, @ornikar/stylelint-config/.eslintrc.json, @ornikar/webpack-config/.eslintrc.json, package.json, yarn.lock
=> refactor: eslint 7 ARCH-1174

@ornikar/renovate-config/package.json
automerge minor and patch for testing-library when CI passes
As they are unit tests, we can be sure if the tests passes it works for us.
=> feat(renovate-config): automerge minor and patch testing library [no issue]

@ornikar/postcss-config/package.json, yarn.lock
fixes issue with multipart values
=> feat(postcss-config): update postcss-custom-properties [no issue]

@ornikar/storybook-config/addons.js, @ornikar/storybook-config/index.js, @ornikar/storybook-config/package.json, @ornikar/storybook-config/webpack-configs/base.js, yarn.lock
BREAKING CHANGE: requires storybook 6
=> feat: storybook 6 ARCH-1277

@ornikar/stylelint-config/styled-components.js, @ornikar/stylelint-config/tests/styled-components/TestComponents.tsx
=> fix(stylelint-config): functions in camelcase INSTRUCTOR-105

@ornikar/jest-config/bin/test-coverage.sh, @ornikar/jest-config/package.json
Reusable script currently in LWA.
=> feat(jest-config): add test-coverage script [no issue]

@ornikar/lerna-config/package.json, yarn.lock
Reverts ornikar/shared-configs#508
=> revert: feat(deps): update dependency @pob/pretty-eslint-config to v2 [no issue]

@ornikar/storybook-config/index.js
avoid postcss issues in storybook for webapps
Conditionally apply postcss addon
=> fix: do not apply postcss addon if cra preset is present [no issue]

@ornikar/storybook-config/defaultParameters.js
We use @ornikar/react-storybook when we need paddings, else we need fullscreen
=> feat(storybook-config): default layout fullscreen [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
- support for monorepo with apps
- support for examples in monorepo (private packages that are not meant to be published)
=> feat(lerna-config): support monorepo with apps or examples [no issue]

@ornikar/repo-config/createLintStagedConfig.js
=> fix(repo-config): allow repo to have no tsconfig.build.json for prettier [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js, @ornikar/lerna-config/index.js
Currenlty tsconfig changes often
Sort package using lerna graph to keep the same order every time
=> fix(lerna-config): sort packages [no issue]

@ornikar/repo-config/createLintStagedConfig.js
=> fix(repo-config): fix lint-staged warnings [no issue]

@ornikar/storybook-config/webpack-configs/lib.js
fix when you want to import another file than index.{ts,js}
=> fix(storybook-config): alias is a regexp [no issue]

@ornikar/storybook-config/package.json, yarn.lock
It will be easier to handle all storybook versions in root package.json
=> fix(storybook-config): move addon-essentials to peer dep to avoid duplicates [no issue]

@ornikar/rollup-config/createRollupConfig.js
only create builds for node 14 as we no longer supports node 12
=> feat(rollup-config): build for node 14 [no issue]

@ornikar/rollup-config/createRollupConfig.js
Build separate dist for react-native platforms by resolving platform-specific extensions
=> feat(rollup-config): react-native builds [no issue]

@ornikar/rollup-config/createRollupConfig.js
Setting in package.json:
```
{
"ornikar": { "entries": ["index", "other-entry"] }
}
```
Allows to build for both src/index.ts and src/other-entry.ts
=> feat(rollup-config): support multiple entries [no issue]

@ornikar/rollup-config/createRollupConfig.js
=> fix(rollup-config): replace options [no issue]

.circleci/config.yml
https://github.com/github/renaming
=> ci: main [no issue]

@ornikar/rollup-config/createRollupConfig.js, @ornikar/rollup-config/package.json, yarn.lock
Enable babel-plugin-styled-components for web only
=> feat(rollup-config): add babel-plugin-styled-components [no issue]

@ornikar/lerna-config/index.js
ts config is constantly changing
sort package by name, on each iteration, to keep them in the same order
=> fix(lerna-config): sort packages to prevent random changes [no issue]

@ornikar/intl-config/generate-translations.js
…efault messages [no issue]
If we have the same translation ID in web / android / ios component than the regular version, and the defaultMessage is the same, we should not crash the aggregate-translations script
Let this case pass
=> feat: let identical translations pass if from similar file and same default messages [no issue]

@ornikar/intl-config/generate-translations.js
Phrase YAML is beginning to feel clunky, and hard to maintain.
Let's automatise the sources and targets parts
=> feat: generate translations script returns a part of phrase config [no issue]

@ornikar/jest-config/jest-global-setup.ts, @ornikar/jest-config/jest-preset.js
=> feat(jest-config): set timezone to utc in config [no issue]

@ornikar/jest-config-react-native-web/package.json, @ornikar/jest-config-react/jest-preset.js, @ornikar/jest-config-react/package.json, @ornikar/jest-config/package.json, yarn.lock
This pr proposes a few fixes to be able to use the jest configs in kitt-universal
=> fix: shared configs/fix jest configs CME-51

@ornikar/lerna-config/bin/generate-tsconfig-files.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3001386228/2021-12-21
https://app.pitch.com/app/presentation/a4be2095-b319-45e7-8462-be0e14851b01/e357537e-0c3c-4060-8ede-699c37aea857
=> feat(lerna-config): use react-jsx in tsconfig [no issue]

@ornikar/lerna-config/index.js
be able to get packages locations and content synchronously
add `getSyncPackages` and `getSyncPackageLocations`
=> feat(lerna-config): get sync packages [no issue]

@ornikar/repo-config/lib/postinstall/install-husky.js
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3001386228/2021-12-21
=> feat(repo-config): add native lockfiles [no issue]

.husky/post-checkout, .husky/post-merge, .husky/post-rewrite, @ornikar/repo-config/lib/postinstall/install-husky.js
fix issue when cd to package but not returning to root + better spacing
=> fix(repo-config): cd package location [no issue]

@ornikar/lerna-config/bin/generate-eslintrc-files.js, @ornikar/lerna-config/bin/generate-tsconfig-files.js
More permanent fix than https://github.com/ornikar/learner-apps/pull/3344
=> fix(lerna-config): fix eslint by not using tsc cache [no issue]

@ornikar/rollup-config/createRollupConfig.js
like css modules currently works, prefix styles for linaria
Tested in kitt-universal
=> feat(rollup-config): configure classNameSlug ARCH-1503

@ornikar/jest-config-react-native/customTransforms.js, @ornikar/storybook-config/addon/defaultOptions.js, @ornikar/storybook-config/addon/webpackFinal.js, @ornikar/storybook-config/index.js, @ornikar/storybook-config/webpack-configs/fixStorybookBabelRules.js, @ornikar/webpack-config/linaria.js, @ornikar/webpack-config/reactNativeWeb.js
Permet de gagner ~10s sur les storybook mais finalement peu de diffs pour les apps.
Ca permet quand meme de clean les configs.
=> feat(webpack-config): improve config for faster webpack ARCH-1515

.husky/pre-push, @ornikar/repo-config/lib/postinstall/install-husky.js
pre push hook is way too slow if we run all tests, and it doesn't make sense to run them all
Only run tests related to files that changed between this branch and main
=> feat: pre-push only run test changed since main branch [no issue]

@ornikar/renovate-config/package.json
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3272376346/2022-06-07
Note: eslint-configs "repository" field is configured via yo in this commit: https://github.com/ornikar/eslint-configs/commit/d6604f7df0666e3ff12e5ef2af8f4ba7af2f79d6
=> feat(renovate-config): configure team frontend-shared-components-maintainers [no issue]

.husky/pre-push, @ornikar/repo-config/lib/postinstall/install-husky.js
Si git n'est pas en anglais le hook de pre-push fail
On force la LANG à en_US
=> feat: force git language on husky pre push hook [no issue]

.github/workflows/release-alert.yml
Mauvais linting avec l'éditeur github Actions
fix
=> fix: release alert action linting

@ornikar/jest-config-react/__mocks__/@storybook/react.js
fix error console saying we use act without await
=> fix(jest-config-react): fix act without await [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.js
Adapt this generator for vitrine, a legacy project
=> feat(lerna-config): adapt generator for legacy project [no issue]

@ornikar/postcss-config/README.md
Previous release introduced by #792 should have been breaking but I made a mistake.
Update readme
=> fix: previous release was breaking [no issue]

.github/CODEOWNERS
- https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3411607717/Maintainers
- https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3456139296/Chapter+Frontend+Education+5+-+03+10+2022
- https://github.com/orgs/ornikar/teams/frontend-configs-maintainers/members
=> chore: add codeowners ARCH-1581

@ornikar/jest-config-react/jest-preset.js
Tested everywhere, it works well
https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3412952239/2022+09+22+-+Tests+Working+Group
=> feat(jest-config-react): configure default max workers ECF-61

@ornikar/jest-config/jest-preset.js
Set `clearMocks` to `true`. Discussed in the last test's WG https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3514140298/2022+11+17+-+Tests+Working+Group
=> feat(jest-config): add clearMocks config INSTRUCTOR-1858

@ornikar/jest-config-react-native/__mocks__/@storybook/addon-actions.js, @ornikar/jest-config-react-native/__mocks__/@storybook/addons.js, @ornikar/jest-config-react-native/jest-preset.js, @ornikar/jest-config-react/__mocks__/@storybook/addon-actions.js, @ornikar/jest-config-react/__mocks__/@storybook/addons.js, @ornikar/jest-config-react/jest-preset.js
Add missing storybook mocks to prevent storybook leaks in jest
=> feat(jest-config-react): add storybook mocks [no issue]

renovate.json
Configure renovate https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3411607717/Frontend+Maintainers
=> chore: update renovate config [no issue]

.vscode/extensions.json, .vscode/shared-configs.code-workspace, @ornikar/repo-config-react-legacy-css/createLintStagedConfig.js, @ornikar/repo-config-react-legacy-css/package.json, @ornikar/repo-config-react/package.json, yarn.lock
BREAKING CHANGE: if you used css files, replace repo-config-react by repo-config-react-legacy-css
=> feat(repo-config-react)!: create repo-config-react-legacy-css with typed-css-modules [no issue]

@ornikar/renovate-config/package.json
Configure token for all repositories via this shared package
=> feat(renovate-config): configure npm token for yarn berry [no issue]

@ornikar/lerna-config/bin/generate-tsconfig-files.mjs
https://twitter.com/mattpocockuk/status/1680884391977922561?s=46&t=U1iqriwt8foODajmkxIApg
=> feat(lerna-config): generate tsconfig module detection to force [no issue]

@ornikar/jest-config-react-native/web/jest-preset.js, @ornikar/jest-config-react/jest-preset.js
similar to https://github.com/ornikar/shared-configs/pull/935 but for web.
exports documentation: https://ornikar.atlassian.net/wiki/spaces/TECH/pages/3402531190/How+to+configure+library+exports
=> feat(jest-config-react): configure export custom conditions for web [no issue]

@ornikar/jest-config/bin/ornikar-run-jest.mjs, @ornikar/jest-config/package.json, yarn.lock
=> feat(jest-config): add ornikar-run-jest [no issue]

@ornikar/rollup-config/createRollupConfig.js
https://ornikar.slack.com/archives/C04FN79S43W/p1700065663007449
issue when we have 2 versions of react-native-reanimated: one for expo go and one for our expo dev client.
Change rollup config to allow react-native-reanimated babel plugin to work on the app'side with the distribution rollup file for metro.
=> feat(rollup-config)!: change react-native builds for metro [no issue]

@ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx, @ornikar/jest-config-react/__mocks__/@storybook/react.js
Add the ability to use `beforeAll` in stories, through `parameters`.
=> feat(jest-config-react-native): add beforeAll parameters [no issue]

@ornikar/jest-config-react-native/package.json, yarn.lock
Upgrade deps for jest-expo and react-native to match expo sdk 49
=> feat!: expo 49 OSE-1664
